server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: spring-boot-realm
  resource: spring-boot-client
  credentials:
    secret: R2Ch7I4ROmyHw2LNA6FRgUptkcOPOLGW
  public-client: false
  ssl-required: external
  use-resource-role-mappings: true
spring:
  application:
    name: auth
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/spring-boot-realm
        registration:
          keycloak:
            client-id: spring-boot-client
            client-secret: R2Ch7I4ROmyHw2LNA6FRgUptkcOPOLGW
            scope: openid, profile, email
            redirect-uri: http://localhost:8080/*
