server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:8080
  realm: auth-realm
  resource: auth-gateway
  credentials:
    secret: Q9EZORTzFm5hBw0aTrLpvaBM0fwqOzWk
  public-client: false
  ssl-required: external
  use-resource-role-mappings: true
  bearer-only: true
  principal-attribute: preferred_username
#  policy-enforcer-config: {
#    "http-method-as-scope": true
#  }

spring:
  application:
    name: auth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth?useSSL=false
    username: auth
    password: auth
    jpa:
      hibernate:
        properties:
          ddl-auto: none
  liquibase:
    change-log: classpath:db/main.xml
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/auth-realm
        registration:
          keycloak:
            client-id: auth-gateway
            client-secret: Q9EZORTzFm5hBw0aTrLpvaBM0fwqOzWk
            scope: openid, profile, email
            redirect-uri: http://localhost:8080/*

  main:
    allow-circular-references: true
logging:
  level:
    org.keycloak: DEBUG
    org.springframework.security: DEBUG
